### ISSUE TITLE
Request: Convert build to Maven or Gradle

### ISSUE THREAD

**Issue by drichelson** [heronarts/LX#17]
This makes for zero effort import into IDEs and makes for easy publishing of jars which makes importing LX into a project much easier. I'm happy to do this work if you will consider merging it.

**Comment by mcslee** [comment]
Hey Dan - yep I'd be happy to merge this. I would still want to keep the simple ant build scripts around, but totally happy to have this also integrate with the more modern build systems. I haven't managed to prioritize this, if you are familiar and have time to quickly whip it up that'd be great.

**Comment by nargetdev** [comment]
Did this ever happen?  Would be happy to take a crack at it if no.

**Comment by mcslee** [comment]
Yup - everything is Mavenized, and releases are published to Maven Central.
https://search.maven.org/search?q=g:com.heronarts

How you doing @nargetdev? Got LX projects in the works these days?
