### ISSUE TITLE
Feature request: Add visual aid to heronarts.lx.color.ColorParameter

### ISSUE THREAD

**Issue by drichelson** [heronarts/LX#20]
This is a handy widget! it would be cool to add a visual aid so that it's clear what color is represented by the 3 parameters. One thought is to group them and make their background the currently selected color..
I realize at least part of this implementation would happen in P3LX..

**Comment by mcslee** [comment]
Hey Dan - just want to make sure I understand what you're asking about here. Which thing are you referring to as the handy widget? Do you just mean the ColorParameter helper itself, or are you referring to one of the existing color-selection UIs?

Shoot me a screen-shot perhaps of which bit you're talking about?

**Comment by drichelson** [comment]
I'm referring to the ColorParameter helper class itself. Here is a screenshot with a box drawn around the 3 knobs for my ColorParameter:
![image](https://user-images.githubusercontent.com/602409/51711841-fa5cd000-1fe1-11e9-89a7-4ef5b91d8805.png)
1. It would be cool to add a box like I did so the grouping of them is more intuitive.
2. It would also be cool to have something indicating the currently selected color.

It could also be cool to have this involve a color picker, but maintain support for modulation...

**Comment by mcslee** [comment]
Gotcha. I made something for this once, but I should really make it more generic. There's a custom color picker UI for the SolidPattern class in P3LX.

https://github.com/heronarts/P3LX/blob/master/src/main/java/heronarts/p3lx/pattern/SolidPattern.java

<img width="362" alt="screen shot 2019-01-24 at 2 42 51 pm" src="https://user-images.githubusercontent.com/597850/51713335-70fbcc80-1fe6-11e9-90cf-7142f9caa4eb.png">

This could probably be more dense, it's kind of a big UI. I could def make this this into a single reusable component though. Would that work for you?

**Comment by drichelson** [comment]
Nice! that looks good. My particular pattern has multiple colors and I'd like to oscillate their values independently.

**Comment by mcslee** [comment]
Cool - on my TODO list to make this generic. Coming soon...

Feel free to just hijack that code in the meantime if you like.

**Comment by jkbelcher** [comment]
Upvote to make this generic and easy to use.  I frequently have 1-2 HSB colors as pattern parameters so would use this often.  Thanks!

**Comment by drichelson** [comment]
I'm resurfacing after a long break from LX etc. Is this still outstanding? If so I may take a stab at building it.

**Comment by mcslee** [comment]
Hey Dan! There is a UIColorPicker helper for this now:
https://github.com/heronarts/P3LX/blob/dev/src/main/java/heronarts/p3lx/ui/component/UIColorPicker.java

Might not be exactly what you're looking for, but renders a color box which you can click on for a context menu with more detailed color section controls (which should be midi/modulation-mappable).
