### ISSUE TITLE
Tempo bug with OSC clocksource

### ISSUE THREAD

**Issue by jkbelcher** [heronarts/LX#31]
When tempo.clocksource is set to OSC, it appears tempo is still ramping at the speed set by tempo.bpm.  For example, if tempo.bpm is manually set to 20 with the ui, and the external source driving OSC beats is running at 80 bpm, then tempo.ramp will only reach a value of .25 between beats.

Also, if the bpm is set to a higher frequency than the external OSC source, then an extra beat fires between every external beat.  The timing of this beat is (1/tempo.bpm) seconds after the external beat.  In this case tempo.ramp starts at 0 on the external beat, increases at the tempo.bpm rate until it reaches 1, then the extra beat fires, then tempo.ramp remains at 1 until it is reset by the next external beat.

This looks like two items to fix:
1) When tempo.clocksource is set to OSC, only fire a beat when it is received from the OSC source.  Don't fire based on time elapsed since the last beat.
2) When tempo.clocksource is set to OSC, calculate tempo.bpm and tempo.ramp on a continuous basis based on timing between OSC beats.

Alternatively for item 2, an external source that already knows the bpm could pass the bpm value as an additional OSC parameter and save LX from doing a redundant calculation.

**Comment by mcslee** [comment]
Yeah - agreed it would be good to have a "learn" mode here where the OSC spacing is recognized and the tempo updated.

FYI you *should* be able to manually update the BPM directly via OSC sending a message with a bpm value, eg.:
/lx/tempo/bpm 132

Then the ramp timing will respect that value.

The extra-beat-firing bug I've got to think about a bit. My intuition was that the clock should not completely stop and freeze up if the OSC messages stop being received, but rather it should just continue at its established BPM. However, this is maybe awkward and per this bug, it might be better when in OSC mode to just *only* beat upon explicitly OSC messages.

**Comment by jkbelcher** [comment]
Looks like an OSC message to /lx/tempo/bpm is wanting values in the 0-1 range, rather than the raw bpm value.  But yes that will solve the ramp timing.

It makes sense to me, when in OSC mode, to only fire beats on explicit OSC messages.  This way if the external equipment is paused LX will pause as well.

**Comment by mcslee** [comment]
Ah yeah, I forgot this was on my TODO list prior. Yeah the BPM value is unfortunately normalized, which is obviously not intuitive. I'll add a separate OSC message to set it as a "real" tempo value.

And upon further consideration I think you're right that the behavior in OSC mode should be to just only fire on explicit message. Will make that change.

**Comment by mcslee** [comment]
Added a new OSC endpoint to set tempo in real BPM numbers:
https://github.com/heronarts/LX/commit/3155439c9ace669b4d98f672ce6dd953258142b2

e.g. "/lx/tempo/setBPM 120"

As for the extra-beat issue, are you running against latest version? In my testing, the tempo object is not looping in MIDI/OSC clock mode, per this line of code:
https://github.com/heronarts/LX/blob/master/LX/src/main/java/heronarts/lx/Tempo.java#L218

Are you sure you're running against the latest?
