### ISSUE TITLE
Storing more than 5 clips in a channel?

### ISSUE THREAD

**Issue by worldveil** [heronarts/LX#70]
Currently in LX studio, I can only record and store 5 clips per channel. 

Is there a way to hold more? I don't mind if they aren't always visible, just want them to be programmatically available. 

The work around is to just create a bunch of channels to keep holding more but that's kind of hacky.

**Comment by mcslee** [comment]
Yeah this was me being super lazy when I first implemented those, and then never coming back to it. It's pretty high on my priority list now though, and I'll try to bump it considering you'd use it. Hopefully after I finish up this performance mode APC stuff.

**Comment by mcslee** [comment]
FYI - still on my TODO list, but I realized that programmatic access on an LXBus is *not* limited to 5. You should totally be fine to call `addClip` etc. programmatically and put more in there. They just won't show up in the UI, and the mixer will still only have 5 SCENE launch buttons.

I'm going to fix all that as well, but just an FYI here that there are no limits inside `LXBus` itself. (When I eventually fix all that I'll probably add an upper bound... as e.g. adding a million empty clips is probably not a good idea.)

**Comment by mcslee** [comment]
This is now fully dynamic with UI to add/remove extra scenes and to scroll them.
https://github.com/heronarts/LX/commit/8ad0c2e7b53f7c810cabc2ff451fef5f


<img width="251" alt="Screen Shot 2022-08-04 at 11 55 26 AM" src="https://user-images.githubusercontent.com/597850/182931350-e55cfec3-927e-41fb-a525-9877ebc3efbe.png">
b0949543
