### ISSUE TITLE
/lx/tempo/beat OSC messages sending when OSC output is disabled

### ISSUE THREAD

**Issue by jkbelcher** [heronarts/LX#94]
To reproduce:

- Set Tempo clock source to INT
- Turn on OSC output
- Turn off OSC output
- /lx/tempo/beat messages continue to send

**Comment by mcslee** [comment]
Nice catch - fixed up: https://github.com/heronarts/LX/commit/b65d4dc9e59799110dd28b6dc170713788ea92ab
